changesetBaseRefs:
  - next
  - origin/next
  - upstream/next

changesetIgnorePatterns:
  - '**/*.test.{js,ts}'
  - '**/*.spec.{js,ts}'

defaultSemverRangePrefix: ''

enableGlobalCache: false

nmMode: hardlinks-local

nodeLinker: node-modules

npmRegistryServer: 'https://registry.npmjs.org/'
npmPublishRegistry: "https://npm.pkg.github.com"

supportedArchitectures:
  cpu:
    - current
  os:
    - current

yarnPath: .yarn/releases/yarn-4.0.0-rc.6.cjs

logFilters:
  - code: YN0013
    level: discard
  - text: ^cypress*
    level: discard
  - text: ^@sentry*
    level: discard
